# Generated by Django 5.0.6 on 2024-06-03 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_cat_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
