# Generated by Django 5.0.6 on 2024-06-09 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_cat_is_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.user'),
        ),
    ]
