# Generated by Django 5.0.1 on 2024-06-18 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cats',
            name='spayed',
            field=models.CharField(max_length=10),
        ),
    ]
