# Generated by Django 4.2.10 on 2024-04-06 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_addresses'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='addresses',
            table='addresses',
        ),
    ]
