# Generated by Django 4.2.10 on 2024-04-06 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_orders_orderitems'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='addresses',
            unique_together=set(),
        ),
    ]
